apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service-backend-test-demo
spec:
  selector:
    matchLabels:
      run: master-service-backend-test-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: master-service-backend-test-demo
    spec:
      containers:
      - name: master-service-backend-test-demo
        image: __IMAGE__
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: master-service-backend-test-demo
  labels:
    run: master-service-backend-test-demo
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  type: ClusterIP
  selector:
    run: master-service-backend-test-demo
